name: Run CI
on:
  workflow_dispatch:
  push:
    branches: [ rlamb/github-ci-and-release ]
    paths-ignore:
      - '**.md' # Do not need to run CI for markdown changes.
  pull_request:
    branches: [ rlamb/github-ci-and-release ]
    paths-ignore:
      - '**.md'

jobs:
  ci-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # If you only need the current version keep this.

      - uses: ./.github/actions/ci
